name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Install ALSA headers
      run: sudo apt-get install -y libasound2-dev
    - uses: actions/checkout@v3
    - name: Clippy
      run: cargo clippy --benches --examples --all-targets -- -D warnings -D clippy::dbg_macro
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
